name: Auto Cherry-Pick from Upstream

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to create the PR against"
        required: true
        default: "main"
      mode:
        description: "Run mode: cherry-pick or verify"
        required: false
        default: "cherry-pick"
      script:
        description: "Specify the npm/yarn script to run if available"
        required: false
        type: string
        default: "yarn build"
      package_manager:
        description: "Specify package manager if available (npm or yarn or pnpm)"
        required: false
        type: string
        default: "yarn"
      yarn_version:
        required: false
        type: string
        default: "3.6.3"
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  cherry-pick:
    if: github.event_name == 'workflow_dispatch' || contains(fromJson(toJson(github.event.pull_request.labels)).*.name, 'review-required')
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@v1
    with:
      original-owner: "crazy-max"
      repo-name: "ghaction-github-status"
      base_branch: ${{ inputs.base_branch }}
      mode: ${{ github.event_name == 'pull_request' && 'verify' || inputs.mode }}
      script: ${{ inputs.script || 'yarn build' }}
      yarn_version: ${{ inputs.yarn_version || '3.6.3' }}
      package_manager: ${{ inputs.package_manager || 'yarn' }}
